services:
  proxy:
    image: nginx:latest
    container_name: nginx-proxy-gkj
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/carol/projectKPWS/webgereja-tailwind/frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - gkj-network

  backend:
    build: ./backend
    container_name: backend-gkj
    restart: always
    environment:
      - PORT=5001
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=kpGKJws@2025
      - DB_NAME=gkjwatesselatan
    depends_on:
      - mysql
    networks:
      - gkj-network

  mysql:
    image: mysql:8.0
    container_name: mysql-gkj
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kpGKJws@2025
      MYSQL_DATABASE: gkjwatesselatan
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gkj-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - gkj-network

volumes:
  mysql_data:

networks:
  gkj-network:
    driver: bridge
